axxiaarm64/atf-axxia: drop PROVIDES from atf-axxia layer
Issue: LIN1024-5818

After PREFERRED_PROVIDER_virtual/arm-trusted-firmware had been set in
meta-xilinx, it will cuase below error when build u-boot-axxia, because
atf-axxia is specific to axxiaarm, do not need to make it available
outside axxiaarm layer, the default PROVIDES name "atf-axxia" works well
for this bsp.

ERROR: Nothing PROVIDES 'atf-axxia'
atf-axxia was skipped: PREFERRED_PROVIDER_virtual/arm-trusted-firmware set to trusted-firmware-a, not atf-axxia

Signed-off-by: Liwei Song <liwei.song@windriver.com>